version: "2"

services:

    # Partie de l'app frontend
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "3030:3030"
        expose:
            - "80"

    # Partie de l'API produits
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - "3031:3031"

        environment:
            MONGO_URI: mongodb+srv://root:root@cluster0.p7xv1.mongodb.net/cybersecurite?retryWrites=true&w=majority

    # Partie de l'API auth
    auth_api:
        build:
            context: ./auth_api
            dockerfile: Dockerfile
        ports:
            - "3032:3032"

        environment:
            MONGO_URI: mongodb+srv://root:root@cluster0.p7xv1.mongodb.net/cybersecurite?retryWrites=true&w=majority

            
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: db_docker
        ports:
            - 27017:27017

    nginx: 
        image: nginx:latest
        container_name: production_nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
            - 443:443